# action.yml
name: 'Make TCP Connection'
description: 'Test TCP Connectivity'
inputs:
  remotehost:  # id of input
    description: 'IP to connect to'
    required: true
    default: '127.0.0.1'
  remoteport:
    description: 'Port to connect to'
    required: true
    default: '80'
runs:
  using: 'docker'
  image: 'Dockerfile'
