name: Github Action - TCP Test
on: [push]

jobs:
  tcp_connection_test:
    runs-on: ubuntu-latest
    name: A job to test connectivity
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Working Connectivity
        uses: ./ # Uses an action in the root directory
        id: conn
        with:
          remotehost: '1.1.1.1'
          remoteport: '80'
      - name: Test Failing Connectivity
        uses: ./
        id: bad_conn
        with:
          remotehost: '1.1.1.1'
          remoteport: '8675'
        continue-on-error: true